spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: ''
    password: ''
  jpa:
    properties:
      # no need to drop the database first when running h2, this avoids errors in the log
      javax.persistence.schema-generation.database.action: validate
      hibernate:
        default_schema:
        dialect: org.hibernate.dialect.H2Dialect
        # don't log all SQLs when running the tests
        show_sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/db.changelog.xml
    default-schema:
    drop-first: false
